# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'opennft.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NeuroFB(object):
    def setupUi(self, NeuroFB):
        NeuroFB.setObjectName("NeuroFB")
        NeuroFB.resize(1423, 846)
        self.verticalLayout = QtWidgets.QVBoxLayout(NeuroFB)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnInit = QtWidgets.QPushButton(NeuroFB)
        self.btnInit.setObjectName("btnInit")
        self.horizontalLayout_7.addWidget(self.btnInit)
        self.line_3 = QtWidgets.QFrame(NeuroFB)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_7.addWidget(self.line_3)
        self.pbMoreParameters = QtWidgets.QPushButton(NeuroFB)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pbMoreParameters.setFont(font)
        self.pbMoreParameters.setCheckable(True)
        self.pbMoreParameters.setChecked(False)
        self.pbMoreParameters.setFlat(True)
        self.pbMoreParameters.setObjectName("pbMoreParameters")
        self.horizontalLayout_7.addWidget(self.pbMoreParameters)
        self.btnPlugins = QtWidgets.QPushButton(NeuroFB)
        self.btnPlugins.setEnabled(True)
        self.btnPlugins.setObjectName("btnPlugins")
        self.horizontalLayout_7.addWidget(self.btnPlugins)
        self.btnSetup = QtWidgets.QPushButton(NeuroFB)
        self.btnSetup.setEnabled(False)
        self.btnSetup.setObjectName("btnSetup")
        self.horizontalLayout_7.addWidget(self.btnSetup)
        self.line_4 = QtWidgets.QFrame(NeuroFB)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_7.addWidget(self.line_4)
        self.btnStart = QtWidgets.QPushButton(NeuroFB)
        self.btnStart.setEnabled(False)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout_7.addWidget(self.btnStart)
        self.btnStop = QtWidgets.QPushButton(NeuroFB)
        self.btnStop.setEnabled(False)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout_7.addWidget(self.btnStop)
        self.line_2 = QtWidgets.QFrame(NeuroFB)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_7.addWidget(self.line_2)
        self.btnRTQA = QtWidgets.QPushButton(NeuroFB)
        self.btnRTQA.setEnabled(False)
        self.btnRTQA.setObjectName("btnRTQA")
        self.horizontalLayout_7.addWidget(self.btnRTQA)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_7.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.label_13 = QtWidgets.QLabel(NeuroFB)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.leCurrentVolume = QtWidgets.QLineEdit(NeuroFB)
        self.leCurrentVolume.setEnabled(True)
        self.leCurrentVolume.setMaximumSize(QtCore.QSize(30, 16777215))
        self.leCurrentVolume.setAutoFillBackground(False)
        self.leCurrentVolume.setAlignment(QtCore.Qt.AlignCenter)
        self.leCurrentVolume.setReadOnly(True)
        self.leCurrentVolume.setObjectName("leCurrentVolume")
        self.horizontalLayout_7.addWidget(self.leCurrentVolume)
        self.label_7 = QtWidgets.QLabel(NeuroFB)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.leElapsedTime = QtWidgets.QLineEdit(NeuroFB)
        self.leElapsedTime.setEnabled(True)
        self.leElapsedTime.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leElapsedTime.setAlignment(QtCore.Qt.AlignCenter)
        self.leElapsedTime.setReadOnly(True)
        self.leElapsedTime.setObjectName("leElapsedTime")
        self.horizontalLayout_7.addWidget(self.leElapsedTime)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.stackedWidgetMain = QtWidgets.QStackedWidget(NeuroFB)
        self.stackedWidgetMain.setObjectName("stackedWidgetMain")
        self.pageMain = QtWidgets.QWidget()
        self.pageMain.setObjectName("pageMain")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pageMain)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitterMainVer = QtWidgets.QSplitter(self.pageMain)
        self.splitterMainVer.setOrientation(QtCore.Qt.Vertical)
        self.splitterMainVer.setChildrenCollapsible(False)
        self.splitterMainVer.setObjectName("splitterMainVer")
        self.splitterMainHor = QtWidgets.QSplitter(self.splitterMainVer)
        self.splitterMainHor.setOrientation(QtCore.Qt.Horizontal)
        self.splitterMainHor.setChildrenCollapsible(False)
        self.splitterMainHor.setObjectName("splitterMainHor")
        self.frameLeft = QtWidgets.QFrame(self.splitterMainHor)
        self.frameLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLeft.setObjectName("frameLeft")
        self.layoutLeft = QtWidgets.QVBoxLayout(self.frameLeft)
        self.layoutLeft.setContentsMargins(0, 0, 0, 0)
        self.layoutLeft.setObjectName("layoutLeft")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frameLeft)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.shortParams = QtWidgets.QWidget()
        self.shortParams.setEnabled(True)
        self.shortParams.setObjectName("shortParams")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.shortParams)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frameShortParams = QtWidgets.QFrame(self.shortParams)
        self.frameShortParams.setEnabled(False)
        self.frameShortParams.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameShortParams.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameShortParams.setObjectName("frameShortParams")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frameShortParams)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.leSetFile2 = QtWidgets.QLineEdit(self.frameShortParams)
        self.leSetFile2.setObjectName("leSetFile2")
        self.gridLayout_7.addWidget(self.leSetFile2, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frameShortParams)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 0, 0, 1, 1)
        self.btnChooseSetFile2 = QtWidgets.QPushButton(self.frameShortParams)
        self.btnChooseSetFile2.setMaximumSize(QtCore.QSize(32, 16777215))
        self.btnChooseSetFile2.setObjectName("btnChooseSetFile2")
        self.gridLayout_7.addWidget(self.btnChooseSetFile2, 0, 2, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_7)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_39 = QtWidgets.QLabel(self.frameShortParams)
        self.label_39.setObjectName("label_39")
        self.gridLayout_10.addWidget(self.label_39, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sbNFRunNr2 = QtWidgets.QSpinBox(self.frameShortParams)
        self.sbNFRunNr2.setMaximum(9999)
        self.sbNFRunNr2.setObjectName("sbNFRunNr2")
        self.horizontalLayout_5.addWidget(self.sbNFRunNr2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_37 = QtWidgets.QLabel(self.frameShortParams)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_5.addWidget(self.label_37)
        self.sbImgSerNr2 = QtWidgets.QSpinBox(self.frameShortParams)
        self.sbImgSerNr2.setMaximum(9999)
        self.sbImgSerNr2.setObjectName("sbImgSerNr2")
        self.horizontalLayout_5.addWidget(self.sbImgSerNr2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_5.setStretch(4, 1)
        self.gridLayout_10.addLayout(self.horizontalLayout_5, 0, 1, 1, 1)
        self.leFirstFile2 = QtWidgets.QLineEdit(self.frameShortParams)
        self.leFirstFile2.setObjectName("leFirstFile2")
        self.gridLayout_10.addWidget(self.leFirstFile2, 1, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.frameShortParams)
        self.label_41.setObjectName("label_41")
        self.gridLayout_10.addWidget(self.label_41, 1, 0, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_10)
        self.verticalLayout_13.addWidget(self.frameShortParams)
        self.stackedWidget.addWidget(self.shortParams)
        self.autoRtqaParams = QtWidgets.QWidget()
        self.autoRtqaParams.setEnabled(True)
        self.autoRtqaParams.setObjectName("autoRtqaParams")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.autoRtqaParams)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frameAutoRtqaParams = QtWidgets.QFrame(self.autoRtqaParams)
        self.frameAutoRtqaParams.setEnabled(False)
        self.frameAutoRtqaParams.setObjectName("frameAutoRtqaParams")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frameAutoRtqaParams)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.btnChooseRoiFolder = QtWidgets.QPushButton(self.frameAutoRtqaParams)
        self.btnChooseRoiFolder.setEnabled(False)
        self.btnChooseRoiFolder.setMaximumSize(QtCore.QSize(32, 16777215))
        self.btnChooseRoiFolder.setObjectName("btnChooseRoiFolder")
        self.gridLayout_12.addWidget(self.btnChooseRoiFolder, 1, 4, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frameAutoRtqaParams)
        self.label_26.setObjectName("label_26")
        self.gridLayout_12.addWidget(self.label_26, 2, 2, 1, 1)
        self.leWatchFolder3 = QtWidgets.QLineEdit(self.frameAutoRtqaParams)
        self.leWatchFolder3.setEnabled(False)
        self.leWatchFolder3.setObjectName("leWatchFolder3")
        self.gridLayout_12.addWidget(self.leWatchFolder3, 0, 3, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.frameAutoRtqaParams)
        self.label_44.setEnabled(False)
        self.label_44.setObjectName("label_44")
        self.gridLayout_12.addWidget(self.label_44, 0, 0, 1, 1)
        self.leMCTempl3 = QtWidgets.QLineEdit(self.frameAutoRtqaParams)
        self.leMCTempl3.setObjectName("leMCTempl3")
        self.gridLayout_12.addWidget(self.leMCTempl3, 2, 3, 1, 1)
        self.btnMCTempl3 = QtWidgets.QPushButton(self.frameAutoRtqaParams)
        self.btnMCTempl3.setMaximumSize(QtCore.QSize(32, 16777215))
        self.btnMCTempl3.setObjectName("btnMCTempl3")
        self.gridLayout_12.addWidget(self.btnMCTempl3, 2, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frameAutoRtqaParams)
        self.label_16.setEnabled(False)
        self.label_16.setObjectName("label_16")
        self.gridLayout_12.addWidget(self.label_16, 1, 2, 1, 1)
        self.leRoiFolder = QtWidgets.QLineEdit(self.frameAutoRtqaParams)
        self.leRoiFolder.setEnabled(False)
        self.leRoiFolder.setObjectName("leRoiFolder")
        self.gridLayout_12.addWidget(self.leRoiFolder, 1, 3, 1, 1)
        self.btnChooseWatchFolder3 = QtWidgets.QPushButton(self.frameAutoRtqaParams)
        self.btnChooseWatchFolder3.setEnabled(False)
        self.btnChooseWatchFolder3.setMaximumSize(QtCore.QSize(32, 16777215))
        self.btnChooseWatchFolder3.setObjectName("btnChooseWatchFolder3")
        self.gridLayout_12.addWidget(self.btnChooseWatchFolder3, 0, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frameAutoRtqaParams)
        self.label_15.setEnabled(False)
        self.label_15.setObjectName("label_15")
        self.gridLayout_12.addWidget(self.label_15, 0, 2, 1, 1)
        self.sbNFRunNr3 = QtWidgets.QSpinBox(self.frameAutoRtqaParams)
        self.sbNFRunNr3.setEnabled(False)
        self.sbNFRunNr3.setMaximum(9999)
        self.sbNFRunNr3.setObjectName("sbNFRunNr3")
        self.gridLayout_12.addWidget(self.sbNFRunNr3, 0, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.frameAutoRtqaParams)
        self.label_45.setEnabled(False)
        self.label_45.setObjectName("label_45")
        self.gridLayout_12.addWidget(self.label_45, 1, 0, 1, 1)
        self.sbImgSerNr3 = QtWidgets.QSpinBox(self.frameAutoRtqaParams)
        self.sbImgSerNr3.setEnabled(False)
        self.sbImgSerNr3.setMaximum(9999)
        self.sbImgSerNr3.setObjectName("sbImgSerNr3")
        self.gridLayout_12.addWidget(self.sbImgSerNr3, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frameAutoRtqaParams)
        self.label_17.setEnabled(False)
        self.label_17.setObjectName("label_17")
        self.gridLayout_12.addWidget(self.label_17, 2, 0, 1, 1)
        self.sbVolumesNr3 = QtWidgets.QSpinBox(self.frameAutoRtqaParams)
        self.sbVolumesNr3.setEnabled(False)
        self.sbVolumesNr3.setMaximum(9999)
        self.sbVolumesNr3.setObjectName("sbVolumesNr3")
        self.gridLayout_12.addWidget(self.sbVolumesNr3, 2, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_12)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.sbSkipVol3 = QtWidgets.QSpinBox(self.frameAutoRtqaParams)
        self.sbSkipVol3.setEnabled(False)
        self.sbSkipVol3.setMaximum(9999)
        self.sbSkipVol3.setObjectName("sbSkipVol3")
        self.horizontalLayout_8.addWidget(self.sbSkipVol3)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.label_11 = QtWidgets.QLabel(self.frameAutoRtqaParams)
        self.label_11.setEnabled(False)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.sbMatrixSizeX3 = QtWidgets.QSpinBox(self.frameAutoRtqaParams)
        self.sbMatrixSizeX3.setEnabled(False)
        self.sbMatrixSizeX3.setMaximum(9999)
        self.sbMatrixSizeX3.setObjectName("sbMatrixSizeX3")
        self.horizontalLayout_8.addWidget(self.sbMatrixSizeX3)
        self.label_21 = QtWidgets.QLabel(self.frameAutoRtqaParams)
        self.label_21.setEnabled(False)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_8.addWidget(self.label_21)
        self.sbMatrixSizeY3 = QtWidgets.QSpinBox(self.frameAutoRtqaParams)
        self.sbMatrixSizeY3.setEnabled(False)
        self.sbMatrixSizeY3.setMaximum(9999)
        self.sbMatrixSizeY3.setObjectName("sbMatrixSizeY3")
        self.horizontalLayout_8.addWidget(self.sbMatrixSizeY3)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.label_24 = QtWidgets.QLabel(self.frameAutoRtqaParams)
        self.label_24.setEnabled(False)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_8.addWidget(self.label_24)
        self.sbSlicesNr3 = QtWidgets.QSpinBox(self.frameAutoRtqaParams)
        self.sbSlicesNr3.setEnabled(False)
        self.sbSlicesNr3.setMaximum(9999)
        self.sbSlicesNr3.setObjectName("sbSlicesNr3")
        self.horizontalLayout_8.addWidget(self.sbSlicesNr3)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.cbOfflineMode3 = QtWidgets.QCheckBox(self.frameAutoRtqaParams)
        self.cbOfflineMode3.setEnabled(False)
        self.cbOfflineMode3.setObjectName("cbOfflineMode3")
        self.horizontalLayout_8.addWidget(self.cbOfflineMode3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.horizontalLayout_8.setStretch(6, 1)
        self.gridLayout_13.addLayout(self.horizontalLayout_8, 0, 1, 1, 1)
        self.leFirstFile3 = QtWidgets.QLineEdit(self.frameAutoRtqaParams)
        self.leFirstFile3.setEnabled(False)
        self.leFirstFile3.setObjectName("leFirstFile3")
        self.gridLayout_13.addWidget(self.leFirstFile3, 1, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.frameAutoRtqaParams)
        self.label_46.setEnabled(False)
        self.label_46.setObjectName("label_46")
        self.gridLayout_13.addWidget(self.label_46, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frameAutoRtqaParams)
        self.label_18.setEnabled(False)
        self.label_18.setObjectName("label_18")
        self.gridLayout_13.addWidget(self.label_18, 0, 0, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_13)
        self.verticalLayout_14.addWidget(self.frameAutoRtqaParams)
        self.stackedWidget.addWidget(self.autoRtqaParams)
        self.layoutLeft.addWidget(self.stackedWidget)
        self.line_6 = QtWidgets.QFrame(self.frameLeft)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.layoutLeft.addWidget(self.line_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelPlotLegendTitle = QtWidgets.QLabel(self.frameLeft)
        self.labelPlotLegendTitle.setObjectName("labelPlotLegendTitle")
        self.horizontalLayout_4.addWidget(self.labelPlotLegendTitle)
        self.labelPlotLegend = QtWidgets.QLabel(self.frameLeft)
        self.labelPlotLegend.setText("")
        self.labelPlotLegend.setObjectName("labelPlotLegend")
        self.horizontalLayout_4.addWidget(self.labelPlotLegend)
        self.horizontalLayout_4.setStretch(1, 1)
        self.layoutLeft.addLayout(self.horizontalLayout_4)
        self.frameLeftPlots = QtWidgets.QFrame(self.frameLeft)
        self.frameLeftPlots.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameLeftPlots.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLeftPlots.setObjectName("frameLeftPlots")
        self.layoutLeftPlots = QtWidgets.QVBoxLayout(self.frameLeftPlots)
        self.layoutLeftPlots.setContentsMargins(0, 0, 0, 0)
        self.layoutLeftPlots.setObjectName("layoutLeftPlots")
        self.layoutPlot1 = QtWidgets.QVBoxLayout()
        self.layoutPlot1.setObjectName("layoutPlot1")
        self.layoutLeftPlots.addLayout(self.layoutPlot1)
        self.layoutPlot2 = QtWidgets.QVBoxLayout()
        self.layoutPlot2.setContentsMargins(-1, -1, 0, -1)
        self.layoutPlot2.setObjectName("layoutPlot2")
        self.layoutLeftPlots.addLayout(self.layoutPlot2)
        self.layoutPlot3 = QtWidgets.QVBoxLayout()
        self.layoutPlot3.setObjectName("layoutPlot3")
        self.layoutLeftPlots.addLayout(self.layoutPlot3)
        self.layoutLeft.addWidget(self.frameLeftPlots)
        self.layoutLeft.setStretch(3, 1)
        self.frameImages = QtWidgets.QFrame(self.splitterMainHor)
        self.frameImages.setFrameShape(QtWidgets.QFrame.Box)
        self.frameImages.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameImages.setObjectName("frameImages")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frameImages)
        self.verticalLayout_7.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stackedWidgetImages = QtWidgets.QStackedWidget(self.frameImages)
        self.stackedWidgetImages.setObjectName("stackedWidgetImages")
        self.pageMosaic = QtWidgets.QWidget()
        self.pageMosaic.setObjectName("pageMosaic")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.pageMosaic)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.layoutMosaic = QtWidgets.QVBoxLayout()
        self.layoutMosaic.setObjectName("layoutMosaic")
        self.verticalLayout_11.addLayout(self.layoutMosaic)
        self.stackedWidgetImages.addWidget(self.pageMosaic)
        self.pageOrthView = QtWidgets.QWidget()
        self.pageOrthView.setObjectName("pageOrthView")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.pageOrthView)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.layoutOrthView = QtWidgets.QVBoxLayout()
        self.layoutOrthView.setObjectName("layoutOrthView")
        self.verticalLayout_12.addLayout(self.layoutOrthView)
        self.stackedWidgetImages.addWidget(self.pageOrthView)
        self.verticalLayout_7.addWidget(self.stackedWidgetImages)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.posMapCheckBox = QtWidgets.QCheckBox(self.frameImages)
        self.posMapCheckBox.setChecked(True)
        self.posMapCheckBox.setObjectName("posMapCheckBox")
        self.gridLayout.addWidget(self.posMapCheckBox, 0, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 7, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frameImages)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 0, 1, 1)
        self.cbImageViewMode = QtWidgets.QComboBox(self.frameImages)
        self.cbImageViewMode.setEnabled(False)
        self.cbImageViewMode.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cbImageViewMode.setObjectName("cbImageViewMode")
        self.cbImageViewMode.addItem("")
        self.cbImageViewMode.addItem("")
        self.cbImageViewMode.addItem("")
        self.gridLayout.addWidget(self.cbImageViewMode, 0, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.frameImages)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 0, 2, 1, 1)
        self.layoutHotMapThresholds = QtWidgets.QHBoxLayout()
        self.layoutHotMapThresholds.setObjectName("layoutHotMapThresholds")
        self.gridLayout.addLayout(self.layoutHotMapThresholds, 0, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frameImages)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.frameImages)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 1, 2, 1, 1)
        self.layoutNegMapThresholds = QtWidgets.QHBoxLayout()
        self.layoutNegMapThresholds.setObjectName("layoutNegMapThresholds")
        self.gridLayout.addLayout(self.layoutNegMapThresholds, 1, 5, 1, 1)
        self.negMapCheckBox = QtWidgets.QCheckBox(self.frameImages)
        self.negMapCheckBox.setChecked(False)
        self.negMapCheckBox.setObjectName("negMapCheckBox")
        self.gridLayout.addWidget(self.negMapCheckBox, 1, 4, 1, 1)
        self.sliderMapsAlpha = QtWidgets.QSlider(self.frameImages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderMapsAlpha.sizePolicy().hasHeightForWidth())
        self.sliderMapsAlpha.setSizePolicy(sizePolicy)
        self.sliderMapsAlpha.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sliderMapsAlpha.setMaximum(100)
        self.sliderMapsAlpha.setProperty("value", 75)
        self.sliderMapsAlpha.setOrientation(QtCore.Qt.Horizontal)
        self.sliderMapsAlpha.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.sliderMapsAlpha.setObjectName("sliderMapsAlpha")
        self.gridLayout.addWidget(self.sliderMapsAlpha, 1, 1, 1, 1)
        self.roiSelectorBtn = QtWidgets.QPushButton(self.frameImages)
        self.roiSelectorBtn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roiSelectorBtn.sizePolicy().hasHeightForWidth())
        self.roiSelectorBtn.setSizePolicy(sizePolicy)
        self.roiSelectorBtn.setObjectName("roiSelectorBtn")
        self.gridLayout.addWidget(self.roiSelectorBtn, 0, 6, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout.addLayout(self.horizontalLayout, 1, 6, 1, 1)
        self.gridLayout.setColumnStretch(5, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.framePlotMain = QtWidgets.QFrame(self.splitterMainVer)
        self.framePlotMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePlotMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePlotMain.setObjectName("framePlotMain")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.framePlotMain)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layoutPlotMain = QtWidgets.QVBoxLayout()
        self.layoutPlotMain.setObjectName("layoutPlotMain")
        self.verticalLayout_2.addLayout(self.layoutPlotMain)
        self.verticalLayout_4.addWidget(self.splitterMainVer)
        self.stackedWidgetMain.addWidget(self.pageMain)
        self.pageSettings = QtWidgets.QWidget()
        self.pageSettings.setObjectName("pageSettings")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.pageSettings)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(self.pageSettings)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1084, 800))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(0, 0, 13, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frameParams = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frameParams.setEnabled(False)
        self.frameParams.setObjectName("frameParams")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frameParams)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(9)
        self.gridLayout_5.setVerticalSpacing(5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frameParams)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.leSetFile = QtWidgets.QLineEdit(self.frameParams)
        self.leSetFile.setReadOnly(False)
        self.leSetFile.setObjectName("leSetFile")
        self.gridLayout_5.addWidget(self.leSetFile, 0, 2, 1, 1)
        self.btnChooseSetFile = QtWidgets.QPushButton(self.frameParams)
        self.btnChooseSetFile.setObjectName("btnChooseSetFile")
        self.gridLayout_5.addWidget(self.btnChooseSetFile, 0, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem8, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frameParams)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 3, 0, 1, 1)
        self.leWorkFolder = QtWidgets.QLineEdit(self.frameParams)
        self.leWorkFolder.setReadOnly(False)
        self.leWorkFolder.setObjectName("leWorkFolder")
        self.gridLayout_5.addWidget(self.leWorkFolder, 3, 2, 1, 1)
        self.btnChooseWorkFolder = QtWidgets.QPushButton(self.frameParams)
        self.btnChooseWorkFolder.setMaximumSize(QtCore.QSize(32, 16777215))
        self.btnChooseWorkFolder.setObjectName("btnChooseWorkFolder")
        self.gridLayout_5.addWidget(self.btnChooseWorkFolder, 3, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frameParams)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 4, 0, 1, 1)
        self.leProtocolFile = QtWidgets.QLineEdit(self.frameParams)
        self.leProtocolFile.setReadOnly(False)
        self.leProtocolFile.setObjectName("leProtocolFile")
        self.gridLayout_5.addWidget(self.leProtocolFile, 4, 2, 1, 1)
        self.btnChooseProtocolFile = QtWidgets.QPushButton(self.frameParams)
        self.btnChooseProtocolFile.setMaximumSize(QtCore.QSize(32, 16777215))
        self.btnChooseProtocolFile.setObjectName("btnChooseProtocolFile")
        self.gridLayout_5.addWidget(self.btnChooseProtocolFile, 4, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frameParams)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 6, 0, 1, 1)
        self.leWatchFolder = QtWidgets.QLineEdit(self.frameParams)
        self.leWatchFolder.setReadOnly(False)
        self.leWatchFolder.setObjectName("leWatchFolder")
        self.gridLayout_5.addWidget(self.leWatchFolder, 6, 2, 1, 1)
        self.btnChooseWatchFolder = QtWidgets.QPushButton(self.frameParams)
        self.btnChooseWatchFolder.setMaximumSize(QtCore.QSize(32, 16777215))
        self.btnChooseWatchFolder.setObjectName("btnChooseWatchFolder")
        self.gridLayout_5.addWidget(self.btnChooseWatchFolder, 6, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frameParams)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 7, 0, 1, 1)
        self.leRoiAnatFolder = QtWidgets.QLineEdit(self.frameParams)
        self.leRoiAnatFolder.setReadOnly(False)
        self.leRoiAnatFolder.setObjectName("leRoiAnatFolder")
        self.gridLayout_5.addWidget(self.leRoiAnatFolder, 7, 2, 1, 1)
        self.btnChooseRoiAnatFolder = QtWidgets.QPushButton(self.frameParams)
        self.btnChooseRoiAnatFolder.setMaximumSize(QtCore.QSize(32, 16777215))
        self.btnChooseRoiAnatFolder.setObjectName("btnChooseRoiAnatFolder")
        self.gridLayout_5.addWidget(self.btnChooseRoiAnatFolder, 7, 3, 1, 1)
        self.horizontalLayout_RoiAnatW = QtWidgets.QHBoxLayout()
        self.horizontalLayout_RoiAnatW.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_RoiAnatW.setSpacing(6)
        self.horizontalLayout_RoiAnatW.setObjectName("horizontalLayout_RoiAnatW")
        self.label_RoiAnatOperation = QtWidgets.QLabel(self.frameParams)
        self.label_RoiAnatOperation.setObjectName("label_RoiAnatOperation")
        self.horizontalLayout_RoiAnatW.addWidget(self.label_RoiAnatOperation)
        self.leRoiAnatOperation = QtWidgets.QLineEdit(self.frameParams)
        self.leRoiAnatOperation.setObjectName("leRoiAnatOperation")
        self.horizontalLayout_RoiAnatW.addWidget(self.leRoiAnatOperation)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_RoiAnatW.addItem(spacerItem9)
        self.gridLayout_5.addLayout(self.horizontalLayout_RoiAnatW, 8, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frameParams)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 9, 0, 1, 1)
        self.leRoiGroupFolder = QtWidgets.QLineEdit(self.frameParams)
        self.leRoiGroupFolder.setReadOnly(False)
        self.leRoiGroupFolder.setObjectName("leRoiGroupFolder")
        self.gridLayout_5.addWidget(self.leRoiGroupFolder, 9, 2, 1, 1)
        self.btnChooseRoiGroupFolder = QtWidgets.QPushButton(self.frameParams)
        self.btnChooseRoiGroupFolder.setMaximumSize(QtCore.QSize(32, 16777215))
        self.btnChooseRoiGroupFolder.setObjectName("btnChooseRoiGroupFolder")
        self.gridLayout_5.addWidget(self.btnChooseRoiGroupFolder, 9, 3, 1, 1)
        self.label_40_1 = QtWidgets.QLabel(self.frameParams)
        self.label_40_1.setObjectName("label_40_1")
        self.gridLayout_5.addWidget(self.label_40_1, 10, 0, 1, 1)
        self.leWeightsFile = QtWidgets.QLineEdit(self.frameParams)
        self.leWeightsFile.setReadOnly(False)
        self.leWeightsFile.setObjectName("leWeightsFile")
        self.gridLayout_5.addWidget(self.leWeightsFile, 10, 2, 1, 1)
        self.btnChhoseWeghts = QtWidgets.QPushButton(self.frameParams)
        self.btnChhoseWeghts.setMaximumSize(QtCore.QSize(32, 16777215))
        self.btnChhoseWeghts.setObjectName("btnChhoseWeghts")
        self.gridLayout_5.addWidget(self.btnChhoseWeghts, 10, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frameParams)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 11, 0, 1, 1)
        self.leStructBgFile = QtWidgets.QLineEdit(self.frameParams)
        self.leStructBgFile.setReadOnly(False)
        self.leStructBgFile.setObjectName("leStructBgFile")
        self.gridLayout_5.addWidget(self.leStructBgFile, 11, 2, 1, 1)
        self.btnChooseStructBgFile = QtWidgets.QPushButton(self.frameParams)
        self.btnChooseStructBgFile.setMaximumSize(QtCore.QSize(32, 16777215))
        self.btnChooseStructBgFile.setObjectName("btnChooseStructBgFile")
        self.gridLayout_5.addWidget(self.btnChooseStructBgFile, 11, 3, 1, 1)
        self.label_101 = QtWidgets.QLabel(self.frameParams)
        self.label_101.setObjectName("label_101")
        self.gridLayout_5.addWidget(self.label_101, 13, 0, 1, 1)
        self.leMCTempl = QtWidgets.QLineEdit(self.frameParams)
        self.leMCTempl.setObjectName("leMCTempl")
        self.gridLayout_5.addWidget(self.leMCTempl, 13, 2, 1, 1)
        self.btnMCTempl = QtWidgets.QPushButton(self.frameParams)
        self.btnMCTempl.setMaximumSize(QtCore.QSize(32, 16777215))
        self.btnMCTempl.setObjectName("btnMCTempl")
        self.gridLayout_5.addWidget(self.btnMCTempl, 13, 3, 1, 1)
        self.label_102 = QtWidgets.QLabel(self.frameParams)
        self.label_102.setObjectName("label_102")
        self.gridLayout_5.addWidget(self.label_102, 14, 0, 1, 1)
        self.leTaskFolder = QtWidgets.QLineEdit(self.frameParams)
        self.leTaskFolder.setObjectName("leTaskFolder")
        self.gridLayout_5.addWidget(self.leTaskFolder, 14, 2, 1, 1)
        self.btnChooseTaskFolder = QtWidgets.QPushButton(self.frameParams)
        self.btnChooseTaskFolder.setMaximumSize(QtCore.QSize(32, 16777215))
        self.btnChooseTaskFolder.setObjectName("btnChooseTaskFolder")
        self.gridLayout_5.addWidget(self.btnChooseTaskFolder, 14, 3, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_5)
        self.line_5 = QtWidgets.QFrame(self.frameParams)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_8.addWidget(self.line_5)
        spacerItem10 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem10)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setHorizontalSpacing(9)
        self.gridLayout_6.setVerticalSpacing(5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.leFirstFilePath = QtWidgets.QLabel(self.frameParams)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.leFirstFilePath.setFont(font)
        self.leFirstFilePath.setText("")
        self.leFirstFilePath.setObjectName("leFirstFilePath")
        self.gridLayout_6.addWidget(self.leFirstFilePath, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frameParams)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 3, 0, 1, 1)
        self.sbVolumesNr = QtWidgets.QSpinBox(self.frameParams)
        self.sbVolumesNr.setMaximum(9999)
        self.sbVolumesNr.setObjectName("sbVolumesNr")
        self.gridLayout_6.addWidget(self.sbVolumesNr, 6, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frameParams)
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 6, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frameParams)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 2, 0, 1, 1)
        self.sbSkipVol = QtWidgets.QSpinBox(self.frameParams)
        self.sbSkipVol.setMaximum(9999)
        self.sbSkipVol.setObjectName("sbSkipVol")
        self.gridLayout_6.addWidget(self.sbSkipVol, 6, 4, 1, 1)
        self.sbNFRunNr = QtWidgets.QSpinBox(self.frameParams)
        self.sbNFRunNr.setMaximum(9999)
        self.sbNFRunNr.setObjectName("sbNFRunNr")
        self.gridLayout_6.addWidget(self.sbNFRunNr, 3, 4, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.frameParams)
        self.label_31.setObjectName("label_31")
        self.gridLayout_6.addWidget(self.label_31, 8, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frameParams)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 3, 3, 1, 1)
        self.leProjName = QtWidgets.QLineEdit(self.frameParams)
        self.leProjName.setObjectName("leProjName")
        self.gridLayout_6.addWidget(self.leProjName, 0, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frameParams)
        self.label_30.setObjectName("label_30")
        self.gridLayout_6.addWidget(self.label_30, 7, 3, 1, 1)
        self.leSubjectID = QtWidgets.QLineEdit(self.frameParams)
        self.leSubjectID.setObjectName("leSubjectID")
        self.gridLayout_6.addWidget(self.leSubjectID, 0, 4, 1, 1)
        self.leFirstFile = QtWidgets.QLineEdit(self.frameParams)
        self.leFirstFile.setObjectName("leFirstFile")
        self.gridLayout_6.addWidget(self.leFirstFile, 2, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frameParams)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 2, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frameParams)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frameParams)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 6, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frameParams)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 0, 3, 1, 1)
        self.sbTR = QtWidgets.QSpinBox(self.frameParams)
        self.sbTR.setMaximum(9999)
        self.sbTR.setObjectName("sbTR")
        self.gridLayout_6.addWidget(self.sbTR, 8, 1, 1, 1)
        self.horizontalLayout_Matrix = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Matrix.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_Matrix.setSpacing(6)
        self.horizontalLayout_Matrix.setObjectName("horizontalLayout_Matrix")
        self.sbMatrixSizeX = QtWidgets.QSpinBox(self.frameParams)
        self.sbMatrixSizeX.setMaximum(9999)
        self.sbMatrixSizeX.setObjectName("sbMatrixSizeX")
        self.horizontalLayout_Matrix.addWidget(self.sbMatrixSizeX)
        self.label_Matrix = QtWidgets.QLabel(self.frameParams)
        self.label_Matrix.setObjectName("label_Matrix")
        self.horizontalLayout_Matrix.addWidget(self.label_Matrix)
        self.sbMatrixSizeY = QtWidgets.QSpinBox(self.frameParams)
        self.sbMatrixSizeY.setMaximum(9999)
        self.sbMatrixSizeY.setObjectName("sbMatrixSizeY")
        self.horizontalLayout_Matrix.addWidget(self.sbMatrixSizeY)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Matrix.addItem(spacerItem11)
        self.gridLayout_6.addLayout(self.horizontalLayout_Matrix, 7, 4, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frameParams)
        self.label_29.setObjectName("label_29")
        self.gridLayout_6.addWidget(self.label_29, 7, 0, 1, 1)
        self.sbImgSerNr = QtWidgets.QSpinBox(self.frameParams)
        self.sbImgSerNr.setMaximum(9999)
        self.sbImgSerNr.setObjectName("sbImgSerNr")
        self.gridLayout_6.addWidget(self.sbImgSerNr, 2, 4, 1, 1)
        self.sbSlicesNr = QtWidgets.QSpinBox(self.frameParams)
        self.sbSlicesNr.setMaximum(9999)
        self.sbSlicesNr.setObjectName("sbSlicesNr")
        self.gridLayout_6.addWidget(self.sbSlicesNr, 7, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem12, 1, 2, 1, 1)
        self.lbFilePathStatus = QtWidgets.QLabel(self.frameParams)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbFilePathStatus.setFont(font)
        self.lbFilePathStatus.setText("")
        self.lbFilePathStatus.setObjectName("lbFilePathStatus")
        self.gridLayout_6.addWidget(self.lbFilePathStatus, 4, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem13, 5, 2, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_6)
        self.line = QtWidgets.QFrame(self.frameParams)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_8.addWidget(self.line)
        spacerItem14 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem14)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_Offline = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Offline.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_Offline.setSpacing(6)
        self.horizontalLayout_Offline.setObjectName("horizontalLayout_Offline")
        self.cbOfflineMode = QtWidgets.QCheckBox(self.frameParams)
        self.cbOfflineMode.setChecked(True)
        self.cbOfflineMode.setObjectName("cbOfflineMode")
        self.horizontalLayout_Offline.addWidget(self.cbOfflineMode)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Offline.addItem(spacerItem15)
        self.gridLayout_8.addLayout(self.horizontalLayout_Offline, 0, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.frameParams)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_8.addWidget(self.label_38, 0, 1, 1, 1)
        self.cbDataType = QtWidgets.QComboBox(self.frameParams)
        self.cbDataType.setObjectName("cbDataType")
        self.cbDataType.addItem("")
        self.cbDataType.addItem("")
        self.cbDataType.addItem("")
        self.gridLayout_8.addWidget(self.cbDataType, 0, 2, 1, 1)
        self.horizontalLayout_TCP = QtWidgets.QHBoxLayout()
        self.horizontalLayout_TCP.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_TCP.setSpacing(6)
        self.horizontalLayout_TCP.setObjectName("horizontalLayout_TCP")
        self.cbUseTCPData = QtWidgets.QCheckBox(self.frameParams)
        self.cbUseTCPData.setChecked(False)
        self.cbUseTCPData.setObjectName("cbUseTCPData")
        self.horizontalLayout_TCP.addWidget(self.cbUseTCPData)
        self.label_40_11 = QtWidgets.QLabel(self.frameParams)
        self.label_40_11.setObjectName("label_40_11")
        self.horizontalLayout_TCP.addWidget(self.label_40_11)
        self.leTCPDataIP = QtWidgets.QLineEdit(self.frameParams)
        self.leTCPDataIP.setMaximumSize(QtCore.QSize(100, 20))
        self.leTCPDataIP.setText("")
        self.leTCPDataIP.setReadOnly(False)
        self.leTCPDataIP.setObjectName("leTCPDataIP")
        self.horizontalLayout_TCP.addWidget(self.leTCPDataIP)
        self.label_40_2 = QtWidgets.QLabel(self.frameParams)
        self.label_40_2.setObjectName("label_40_2")
        self.horizontalLayout_TCP.addWidget(self.label_40_2)
        self.leTCPDataPort = QtWidgets.QLineEdit(self.frameParams)
        self.leTCPDataPort.setMaximumSize(QtCore.QSize(50, 20))
        self.leTCPDataPort.setText("")
        self.leTCPDataPort.setReadOnly(False)
        self.leTCPDataPort.setObjectName("leTCPDataPort")
        self.horizontalLayout_TCP.addWidget(self.leTCPDataPort)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_TCP.addItem(spacerItem16)
        self.gridLayout_8.addLayout(self.horizontalLayout_TCP, 1, 0, 1, 1)
        self.cbgetMAT = QtWidgets.QCheckBox(self.frameParams)
        self.cbgetMAT.setChecked(False)
        self.cbgetMAT.setObjectName("cbgetMAT")
        self.gridLayout_8.addWidget(self.cbgetMAT, 1, 2, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_8)
        spacerItem17 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem17)
        self.gridLayout_81 = QtWidgets.QGridLayout()
        self.gridLayout_81.setObjectName("gridLayout_81")
        self.horizontalLayout_FB = QtWidgets.QHBoxLayout()
        self.horizontalLayout_FB.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_FB.setSpacing(6)
        self.horizontalLayout_FB.setObjectName("horizontalLayout_FB")
        self.label_37_1 = QtWidgets.QLabel(self.frameParams)
        self.label_37_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37_1.setObjectName("label_37_1")
        self.horizontalLayout_FB.addWidget(self.label_37_1)
        self.cbType = QtWidgets.QComboBox(self.frameParams)
        self.cbType.setObjectName("cbType")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.horizontalLayout_FB.addWidget(self.cbType)
        self.label_41_1 = QtWidgets.QLabel(self.frameParams)
        self.label_41_1.setObjectName("label_41_1")
        self.horizontalLayout_FB.addWidget(self.label_41_1)
        self.leMaxFeedbackVal = QtWidgets.QLineEdit(self.frameParams)
        self.leMaxFeedbackVal.setMaximumSize(QtCore.QSize(50, 20))
        self.leMaxFeedbackVal.setReadOnly(False)
        self.leMaxFeedbackVal.setObjectName("leMaxFeedbackVal")
        self.horizontalLayout_FB.addWidget(self.leMaxFeedbackVal)
        self.label_41_3 = QtWidgets.QLabel(self.frameParams)
        self.label_41_3.setObjectName("label_41_3")
        self.horizontalLayout_FB.addWidget(self.label_41_3)
        self.leMinFeedbackVal = QtWidgets.QLineEdit(self.frameParams)
        self.leMinFeedbackVal.setMaximumSize(QtCore.QSize(50, 20))
        self.leMinFeedbackVal.setReadOnly(False)
        self.leMinFeedbackVal.setObjectName("leMinFeedbackVal")
        self.horizontalLayout_FB.addWidget(self.leMinFeedbackVal)
        self.label_41_2 = QtWidgets.QLabel(self.frameParams)
        self.label_41_2.setObjectName("label_41_2")
        self.horizontalLayout_FB.addWidget(self.label_41_2)
        self.sbFeedbackValDec = QtWidgets.QDoubleSpinBox(self.frameParams)
        self.sbFeedbackValDec.setDecimals(0)
        self.sbFeedbackValDec.setMinimum(0.0)
        self.sbFeedbackValDec.setMaximum(6.0)
        self.sbFeedbackValDec.setProperty("value", 2.0)
        self.sbFeedbackValDec.setObjectName("sbFeedbackValDec")
        self.horizontalLayout_FB.addWidget(self.sbFeedbackValDec)
        self.cbNegFeedback = QtWidgets.QCheckBox(self.frameParams)
        self.cbNegFeedback.setChecked(False)
        self.cbNegFeedback.setObjectName("cbNegFeedback")
        self.horizontalLayout_FB.addWidget(self.cbNegFeedback)
        self.cbFeedbackPlot = QtWidgets.QCheckBox(self.frameParams)
        self.cbFeedbackPlot.setChecked(True)
        self.cbFeedbackPlot.setObjectName("cbFeedbackPlot")
        self.horizontalLayout_FB.addWidget(self.cbFeedbackPlot)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_FB.addItem(spacerItem18)
        self.gridLayout_81.addLayout(self.horizontalLayout_FB, 0, 0, 1, 1)
        self.label_37_2 = QtWidgets.QLabel(self.frameParams)
        self.label_37_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37_2.setObjectName("label_37_2")
        self.gridLayout_81.addWidget(self.label_37_2, 0, 1, 1, 1)
        self.cbProt = QtWidgets.QComboBox(self.frameParams)
        self.cbProt.setObjectName("cbProt")
        self.cbProt.addItem("")
        self.cbProt.addItem("")
        self.cbProt.addItem("")
        self.cbProt.addItem("")
        self.cbProt.addItem("")
        self.gridLayout_81.addWidget(self.cbProt, 0, 2, 1, 1)
        self.horizontalLayout_Sham = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Sham.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_Sham.setSpacing(6)
        self.horizontalLayout_Sham.setObjectName("horizontalLayout_Sham")
        self.label_ShamFile = QtWidgets.QLabel(self.frameParams)
        self.label_ShamFile.setObjectName("label_ShamFile")
        self.horizontalLayout_Sham.addWidget(self.label_ShamFile)
        self.leShamFile = QtWidgets.QLineEdit(self.frameParams)
        self.leShamFile.setMaximumSize(QtCore.QSize(640, 16777215))
        self.leShamFile.setObjectName("leShamFile")
        self.horizontalLayout_Sham.addWidget(self.leShamFile)
        self.btnChooseShamFile = QtWidgets.QPushButton(self.frameParams)
        self.btnChooseShamFile.setMaximumSize(QtCore.QSize(32, 16777215))
        self.btnChooseShamFile.setObjectName("btnChooseShamFile")
        self.horizontalLayout_Sham.addWidget(self.btnChooseShamFile)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_Sham.addItem(spacerItem19)
        self.gridLayout_81.addLayout(self.horizontalLayout_Sham, 1, 0, 1, 1)
        self.horizontalLayout_PTB = QtWidgets.QHBoxLayout()
        self.horizontalLayout_PTB.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_PTB.setSpacing(6)
        self.horizontalLayout_PTB.setObjectName("horizontalLayout_PTB")
        self.cbUsePTB = QtWidgets.QCheckBox(self.frameParams)
        self.cbUsePTB.setChecked(True)
        self.cbUsePTB.setObjectName("cbUsePTB")
        self.horizontalLayout_PTB.addWidget(self.cbUsePTB)
        self.cbScreenId = QtWidgets.QComboBox(self.frameParams)
        self.cbScreenId.setMaximumSize(QtCore.QSize(110, 16777215))
        self.cbScreenId.setObjectName("cbScreenId")
        self.cbScreenId.addItem("")
        self.cbScreenId.addItem("")
        self.horizontalLayout_PTB.addWidget(self.cbScreenId)
        self.cbDisplayFeedbackFullscreen = QtWidgets.QCheckBox(self.frameParams)
        self.cbDisplayFeedbackFullscreen.setChecked(True)
        self.cbDisplayFeedbackFullscreen.setObjectName("cbDisplayFeedbackFullscreen")
        self.horizontalLayout_PTB.addWidget(self.cbDisplayFeedbackFullscreen)
        self.label_33 = QtWidgets.QLabel(self.frameParams)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_PTB.addWidget(self.label_33)
        self.sbTargANG = QtWidgets.QDoubleSpinBox(self.frameParams)
        self.sbTargANG.setMinimum(-99.99)
        self.sbTargANG.setObjectName("sbTargANG")
        self.horizontalLayout_PTB.addWidget(self.sbTargANG)
        self.label_34 = QtWidgets.QLabel(self.frameParams)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_PTB.addWidget(self.label_34)
        self.sbTargRAD = QtWidgets.QDoubleSpinBox(self.frameParams)
        self.sbTargRAD.setMinimum(-99.99)
        self.sbTargRAD.setObjectName("sbTargRAD")
        self.horizontalLayout_PTB.addWidget(self.sbTargRAD)
        self.label_35 = QtWidgets.QLabel(self.frameParams)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_PTB.addWidget(self.label_35)
        self.sbTargDIAM = QtWidgets.QDoubleSpinBox(self.frameParams)
        self.sbTargDIAM.setMinimum(-99.99)
        self.sbTargDIAM.setProperty("value", 10.0)
        self.sbTargDIAM.setObjectName("sbTargDIAM")
        self.horizontalLayout_PTB.addWidget(self.sbTargDIAM)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_PTB.addItem(spacerItem20)
        self.gridLayout_81.addLayout(self.horizontalLayout_PTB, 2, 0, 1, 1)
        self.horizontalLayout_UDP = QtWidgets.QHBoxLayout()
        self.horizontalLayout_UDP.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_UDP.setSpacing(6)
        self.horizontalLayout_UDP.setObjectName("horizontalLayout_UDP")
        self.cbUseUDPFeedback = QtWidgets.QCheckBox(self.frameParams)
        self.cbUseUDPFeedback.setChecked(False)
        self.cbUseUDPFeedback.setObjectName("cbUseUDPFeedback")
        self.horizontalLayout_UDP.addWidget(self.cbUseUDPFeedback)
        self.label_39_1 = QtWidgets.QLabel(self.frameParams)
        self.label_39_1.setObjectName("label_39_1")
        self.horizontalLayout_UDP.addWidget(self.label_39_1)
        self.leUDPFeedbackIP = QtWidgets.QLineEdit(self.frameParams)
        self.leUDPFeedbackIP.setMaximumSize(QtCore.QSize(100, 20))
        self.leUDPFeedbackIP.setText("")
        self.leUDPFeedbackIP.setReadOnly(False)
        self.leUDPFeedbackIP.setObjectName("leUDPFeedbackIP")
        self.horizontalLayout_UDP.addWidget(self.leUDPFeedbackIP)
        self.label_39_2 = QtWidgets.QLabel(self.frameParams)
        self.label_39_2.setObjectName("label_39_2")
        self.horizontalLayout_UDP.addWidget(self.label_39_2)
        self.leUDPFeedbackPort = QtWidgets.QLineEdit(self.frameParams)
        self.leUDPFeedbackPort.setMaximumSize(QtCore.QSize(50, 20))
        self.leUDPFeedbackPort.setText("")
        self.leUDPFeedbackPort.setReadOnly(False)
        self.leUDPFeedbackPort.setObjectName("leUDPFeedbackPort")
        self.horizontalLayout_UDP.addWidget(self.leUDPFeedbackPort)
        self.label_39_3 = QtWidgets.QLabel(self.frameParams)
        self.label_39_3.setObjectName("label_39_3")
        self.horizontalLayout_UDP.addWidget(self.label_39_3)
        self.leUDPFeedbackControlChar = QtWidgets.QLineEdit(self.frameParams)
        self.leUDPFeedbackControlChar.setMaximumSize(QtCore.QSize(50, 20))
        self.leUDPFeedbackControlChar.setText("")
        self.leUDPFeedbackControlChar.setReadOnly(False)
        self.leUDPFeedbackControlChar.setObjectName("leUDPFeedbackControlChar")
        self.horizontalLayout_UDP.addWidget(self.leUDPFeedbackControlChar)
        self.cbUDPSendCondition = QtWidgets.QCheckBox(self.frameParams)
        self.cbUDPSendCondition.setChecked(False)
        self.cbUDPSendCondition.setObjectName("cbUDPSendCondition")
        self.horizontalLayout_UDP.addWidget(self.cbUDPSendCondition)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_UDP.addItem(spacerItem21)
        self.gridLayout_81.addLayout(self.horizontalLayout_UDP, 3, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_81)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem22)
        self.verticalLayout_5.addWidget(self.frameParams)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.stackedWidgetMain.addWidget(self.pageSettings)
        self.verticalLayout.addWidget(self.stackedWidgetMain)

        self.retranslateUi(NeuroFB)
        self.stackedWidgetMain.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.cbScreenId.setCurrentIndex(0)
        self.sbImgSerNr.valueChanged['int'].connect(self.sbImgSerNr2.setValue)
        self.sbNFRunNr2.valueChanged['int'].connect(self.sbNFRunNr.setValue)
        self.sbImgSerNr2.valueChanged['int'].connect(self.sbImgSerNr.setValue)
        self.sbNFRunNr.valueChanged['int'].connect(self.sbNFRunNr2.setValue)
        self.leSetFile2.textChanged['QString'].connect(self.leSetFile.setText)
        self.leSetFile.textChanged['QString'].connect(self.leSetFile2.setText)
        QtCore.QMetaObject.connectSlotsByName(NeuroFB)

    def retranslateUi(self, NeuroFB):
        _translate = QtCore.QCoreApplication.translate
        NeuroFB.setWindowTitle(_translate("NeuroFB", "OpenNFT"))
        self.btnInit.setText(_translate("NeuroFB", "Initialize"))
        self.pbMoreParameters.setText(_translate("NeuroFB", "▼  Review Parameters "))
        self.btnPlugins.setText(_translate("NeuroFB", "Plugins"))
        self.btnSetup.setText(_translate("NeuroFB", "Setup"))
        self.btnStart.setText(_translate("NeuroFB", "Start"))
        self.btnStop.setText(_translate("NeuroFB", "Stop"))
        self.btnRTQA.setText(_translate("NeuroFB", "rtQA"))
        self.label_13.setText(_translate("NeuroFB", "Current Volume"))
        self.leCurrentVolume.setText(_translate("NeuroFB", "0"))
        self.label_7.setText(_translate("NeuroFB", "Processing time (sec)"))
        self.label_5.setText(_translate("NeuroFB", "Setup File"))
        self.btnChooseSetFile2.setText(_translate("NeuroFB", "..."))
        self.label_39.setText(_translate("NeuroFB", "NF Run No"))
        self.label_37.setText(_translate("NeuroFB", "Image Series No"))
        self.label_41.setText(_translate("NeuroFB", "First File Name"))
        self.btnChooseRoiFolder.setText(_translate("NeuroFB", "..."))
        self.label_26.setText(_translate("NeuroFB", "EPI Template"))
        self.label_44.setText(_translate("NeuroFB", "NF Run No"))
        self.btnMCTempl3.setText(_translate("NeuroFB", "..."))
        self.label_16.setText(_translate("NeuroFB", "ROI folder"))
        self.btnChooseWatchFolder3.setText(_translate("NeuroFB", "..."))
        self.label_15.setText(_translate("NeuroFB", "MRI Watch folder"))
        self.label_45.setText(_translate("NeuroFB", "Image Series No"))
        self.label_17.setText(_translate("NeuroFB", "Volumes [n]"))
        self.label_11.setText(_translate("NeuroFB", "Matrix Size [vx]"))
        self.label_21.setText(_translate("NeuroFB", "x"))
        self.label_24.setText(_translate("NeuroFB", "Slices [n]"))
        self.cbOfflineMode3.setText(_translate("NeuroFB", "Offline mode"))
        self.label_46.setText(_translate("NeuroFB", "First File Name"))
        self.label_18.setText(_translate("NeuroFB", "Dummy scans [n]"))
        self.labelPlotLegendTitle.setText(_translate("NeuroFB", "Plot Legend:"))
        self.posMapCheckBox.setText(_translate("NeuroFB", "Positive"))
        self.label_12.setText(_translate("NeuroFB", "View Mode"))
        self.cbImageViewMode.setItemText(0, _translate("NeuroFB", "Mosaic"))
        self.cbImageViewMode.setItemText(1, _translate("NeuroFB", "Triplanar Anatomy"))
        self.cbImageViewMode.setItemText(2, _translate("NeuroFB", "Triplanar EPI"))
        self.label_3.setText(_translate("NeuroFB", "Opacity"))
        self.negMapCheckBox.setText(_translate("NeuroFB", "Negative"))
        self.roiSelectorBtn.setText(_translate("NeuroFB", "ROI select"))
        self.label_2.setText(_translate("NeuroFB", "Setup File"))
        self.btnChooseSetFile.setText(_translate("NeuroFB", "Load Setup File ..."))
        self.label.setText(_translate("NeuroFB", "Work Folder"))
        self.btnChooseWorkFolder.setText(_translate("NeuroFB", "..."))
        self.label_8.setText(_translate("NeuroFB", "Protocol File"))
        self.btnChooseProtocolFile.setText(_translate("NeuroFB", "..."))
        self.label_4.setText(_translate("NeuroFB", "MRI Watch Folder"))
        self.btnChooseWatchFolder.setText(_translate("NeuroFB", "..."))
        self.label_6.setText(_translate("NeuroFB", "ROI Folder (Subject)"))
        self.btnChooseRoiAnatFolder.setText(_translate("NeuroFB", "..."))
        self.label_RoiAnatOperation.setText(_translate("NeuroFB", "ROI Operation"))
        self.leRoiAnatOperation.setToolTip(_translate("NeuroFB", "MATLAB expression. It must contain \'X\', which represents the row vector of activations for each ROI"))
        self.leRoiAnatOperation.setText(_translate("NeuroFB", "median(X)"))
        self.label_9.setText(_translate("NeuroFB", "DCM ROI Folder (Group)"))
        self.btnChooseRoiGroupFolder.setText(_translate("NeuroFB", "..."))
        self.label_40_1.setText(_translate("NeuroFB", "SVM Weights"))
        self.btnChhoseWeghts.setText(_translate("NeuroFB", "..."))
        self.label_10.setText(_translate("NeuroFB", "Underlay Structural File"))
        self.btnChooseStructBgFile.setText(_translate("NeuroFB", "..."))
        self.label_101.setText(_translate("NeuroFB", "Motion Correction Template"))
        self.btnMCTempl.setText(_translate("NeuroFB", "..."))
        self.label_102.setText(_translate("NeuroFB", "Task Folder"))
        self.btnChooseTaskFolder.setText(_translate("NeuroFB", "..."))
        self.label_14.setText(_translate("NeuroFB", "First File Path"))
        self.label_27.setText(_translate("NeuroFB", "Volumes [n]"))
        self.label_25.setText(_translate("NeuroFB", "First File Name"))
        self.label_31.setText(_translate("NeuroFB", "TR [ms]"))
        self.label_19.setText(_translate("NeuroFB", "NF Run No"))
        self.label_30.setText(_translate("NeuroFB", "Matrix Size [vx]"))
        self.label_23.setText(_translate("NeuroFB", "Image Series No"))
        self.label_20.setText(_translate("NeuroFB", "Project Name"))
        self.label_28.setText(_translate("NeuroFB", "Dummy Scans [n]"))
        self.label_22.setText(_translate("NeuroFB", "Subject ID"))
        self.label_Matrix.setText(_translate("NeuroFB", "x"))
        self.label_29.setText(_translate("NeuroFB", "Slices [n]"))
        self.cbOfflineMode.setText(_translate("NeuroFB", "Offline mode"))
        self.label_38.setText(_translate("NeuroFB", "MRI Data Type"))
        self.cbDataType.setItemText(0, _translate("NeuroFB", "DICOM"))
        self.cbDataType.setItemText(1, _translate("NeuroFB", "IMAPH"))
        self.cbDataType.setItemText(2, _translate("NeuroFB", "NII"))
        self.cbUseTCPData.setText(_translate("NeuroFB", "Receive data via TCP"))
        self.label_40_11.setText(_translate("NeuroFB", "IP Address"))
        self.label_40_2.setText(_translate("NeuroFB", "Port"))
        self.cbgetMAT.setText(_translate("NeuroFB", "Calculate MAT"))
        self.label_37_1.setText(_translate("NeuroFB", "NF Feedback Type"))
        self.cbType.setItemText(0, _translate("NeuroFB", "PSC"))
        self.cbType.setItemText(1, _translate("NeuroFB", "DCM"))
        self.cbType.setItemText(2, _translate("NeuroFB", "SVM"))
        self.cbType.setItemText(3, _translate("NeuroFB", "Corr"))
        self.cbType.setItemText(4, _translate("NeuroFB", "None"))
        self.label_41_1.setText(_translate("NeuroFB", "Maximum Feedback Value"))
        self.leMaxFeedbackVal.setText(_translate("NeuroFB", "100"))
        self.label_41_3.setText(_translate("NeuroFB", "Minimum Feedback Value"))
        self.leMinFeedbackVal.setText(_translate("NeuroFB", "-100"))
        self.label_41_2.setText(_translate("NeuroFB", "Number of Decimals"))
        self.cbNegFeedback.setText(_translate("NeuroFB", "Allow Negative Feedback"))
        self.cbFeedbackPlot.setText(_translate("NeuroFB", "Plot Feedback"))
        self.label_37_2.setText(_translate("NeuroFB", "NF Protocol Type"))
        self.cbProt.setItemText(0, _translate("NeuroFB", "Cont"))
        self.cbProt.setItemText(1, _translate("NeuroFB", "ContTask"))
        self.cbProt.setItemText(2, _translate("NeuroFB", "Inter"))
        self.cbProt.setItemText(3, _translate("NeuroFB", "InterBlock"))
        self.cbProt.setItemText(4, _translate("NeuroFB", "Rest"))
        self.label_ShamFile.setText(_translate("NeuroFB", "Sham feedback file"))
        self.btnChooseShamFile.setText(_translate("NeuroFB", "..."))
        self.cbUsePTB.setText(_translate("NeuroFB", "Use PTB MAIN for feedback display on"))
        self.cbScreenId.setItemText(0, _translate("NeuroFB", "Screen 1"))
        self.cbScreenId.setItemText(1, _translate("NeuroFB", "Screen 2"))
        self.cbDisplayFeedbackFullscreen.setText(_translate("NeuroFB", "Fullscreen"))
        self.label_33.setText(_translate("NeuroFB", "Angle"))
        self.label_34.setText(_translate("NeuroFB", "Radius"))
        self.label_35.setText(_translate("NeuroFB", "Diameter"))
        self.cbUseUDPFeedback.setText(_translate("NeuroFB", "Send via UDP"))
        self.label_39_1.setText(_translate("NeuroFB", "IP Address"))
        self.label_39_2.setText(_translate("NeuroFB", "Port"))
        self.label_39_3.setText(_translate("NeuroFB", "Control Character"))
        self.cbUDPSendCondition.setText(_translate("NeuroFB", "Send condition"))

