# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rtqa.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_rtQA(object):
    def setupUi(self, rtQA):
        rtQA.setObjectName("rtQA")
        rtQA.resize(1154, 591)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(rtQA.sizePolicy().hasHeightForWidth())
        rtQA.setSizePolicy(sizePolicy)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(rtQA)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidgetPlots = QtWidgets.QStackedWidget(rtQA)
        self.stackedWidgetPlots.setObjectName("stackedWidgetPlots")
        self.pageSnrPlot = QtWidgets.QWidget()
        self.pageSnrPlot.setObjectName("pageSnrPlot")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pageSnrPlot)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.upperSnrPlot = QtWidgets.QVBoxLayout()
        self.upperSnrPlot.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.upperSnrPlot.setObjectName("upperSnrPlot")
        self.label = QtWidgets.QLabel(self.pageSnrPlot)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.upperSnrPlot.addWidget(self.label)
        self.snrPlotLayout = QtWidgets.QVBoxLayout()
        self.snrPlotLayout.setObjectName("snrPlotLayout")
        self.upperSnrPlot.addLayout(self.snrPlotLayout)
        self.verticalLayout_3.addLayout(self.upperSnrPlot)
        self.stackedWidgetPlots.addWidget(self.pageSnrPlot)
        self.pageMsmdPlot = QtWidgets.QWidget()
        self.pageMsmdPlot.setObjectName("pageMsmdPlot")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pageMsmdPlot)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.fdLabel = QtWidgets.QLabel(self.pageMsmdPlot)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fdLabel.setFont(font)
        self.fdLabel.setObjectName("fdLabel")
        self.verticalLayout_11.addWidget(self.fdLabel)
        self.fdPlotLayout = QtWidgets.QVBoxLayout()
        self.fdPlotLayout.setObjectName("fdPlotLayout")
        self.verticalLayout_11.addLayout(self.fdPlotLayout)
        self.verticalLayout_11.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.tdLabel = QtWidgets.QLabel(self.pageMsmdPlot)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tdLabel.setFont(font)
        self.tdLabel.setObjectName("tdLabel")
        self.verticalLayout_13.addWidget(self.tdLabel)
        self.tdPlotLayout = QtWidgets.QVBoxLayout()
        self.tdPlotLayout.setObjectName("tdPlotLayout")
        self.verticalLayout_13.addLayout(self.tdPlotLayout)
        self.verticalLayout_13.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.rdLabel = QtWidgets.QLabel(self.pageMsmdPlot)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rdLabel.setFont(font)
        self.rdLabel.setObjectName("rdLabel")
        self.verticalLayout_12.addWidget(self.rdLabel)
        self.rdPlotLayout = QtWidgets.QVBoxLayout()
        self.rdPlotLayout.setObjectName("rdPlotLayout")
        self.verticalLayout_12.addLayout(self.rdPlotLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout_12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.stackedWidgetPlots.addWidget(self.pageMsmdPlot)
        self.pageCnrPlot = QtWidgets.QWidget()
        self.pageCnrPlot.setObjectName("pageCnrPlot")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.pageCnrPlot)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.cnrLabel = QtWidgets.QLabel(self.pageCnrPlot)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cnrLabel.setFont(font)
        self.cnrLabel.setObjectName("cnrLabel")
        self.verticalLayout_17.addWidget(self.cnrLabel)
        self.cnrPlotLayout = QtWidgets.QVBoxLayout()
        self.cnrPlotLayout.setObjectName("cnrPlotLayout")
        self.verticalLayout_17.addLayout(self.cnrPlotLayout)
        self.horizontalLayout_7.addLayout(self.verticalLayout_17)
        self.verticalLayout_16.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.labelMean = QtWidgets.QLabel(self.pageCnrPlot)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelMean.setFont(font)
        self.labelMean.setObjectName("labelMean")
        self.verticalLayout_18.addWidget(self.labelMean)
        self.meanPlotLayout = QtWidgets.QVBoxLayout()
        self.meanPlotLayout.setObjectName("meanPlotLayout")
        self.verticalLayout_18.addLayout(self.meanPlotLayout)
        self.horizontalLayout_6.addLayout(self.verticalLayout_18)
        self.verticalLayout_16.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.labelVar = QtWidgets.QLabel(self.pageCnrPlot)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelVar.setFont(font)
        self.labelVar.setObjectName("labelVar")
        self.verticalLayout_19.addWidget(self.labelVar)
        self.varPlotLayout = QtWidgets.QVBoxLayout()
        self.varPlotLayout.setObjectName("varPlotLayout")
        self.verticalLayout_19.addLayout(self.varPlotLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_19)
        self.verticalLayout_16.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_16)
        self.stackedWidgetPlots.addWidget(self.pageCnrPlot)
        self.pageSpikesPlot = QtWidgets.QWidget()
        self.pageSpikesPlot.setObjectName("pageSpikesPlot")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pageSpikesPlot)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.spikesAndStepsPlot = QtWidgets.QVBoxLayout()
        self.spikesAndStepsPlot.setObjectName("spikesAndStepsPlot")
        self.label_2 = QtWidgets.QLabel(self.pageSpikesPlot)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.spikesAndStepsPlot.addWidget(self.label_2)
        self.spikesPlotLayout = QtWidgets.QVBoxLayout()
        self.spikesPlotLayout.setObjectName("spikesPlotLayout")
        self.spikesAndStepsPlot.addLayout(self.spikesPlotLayout)
        self.verticalLayout_7.addLayout(self.spikesAndStepsPlot)
        self.stackedWidgetPlots.addWidget(self.pageSpikesPlot)
        self.pageMsePlot = QtWidgets.QWidget()
        self.pageMsePlot.setObjectName("pageMsePlot")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pageMsePlot)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.mseLayout = QtWidgets.QVBoxLayout()
        self.mseLayout.setObjectName("mseLayout")
        self.label_3 = QtWidgets.QLabel(self.pageMsePlot)
        self.label_3.setMaximumSize(QtCore.QSize(949, 250))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.mseLayout.addWidget(self.label_3)
        self.msePlotLayout = QtWidgets.QVBoxLayout()
        self.msePlotLayout.setObjectName("msePlotLayout")
        self.mseLayout.addLayout(self.msePlotLayout)
        self.verticalLayout_8.addLayout(self.mseLayout)
        self.stackedWidgetPlots.addWidget(self.pageMsePlot)
        self.pageLinearTrendPlot = QtWidgets.QWidget()
        self.pageLinearTrendPlot.setObjectName("pageLinearTrendPlot")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.pageLinearTrendPlot)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.linearTrendLayout = QtWidgets.QVBoxLayout()
        self.linearTrendLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.linearTrendLayout.setContentsMargins(0, -1, -1, -1)
        self.linearTrendLayout.setSpacing(6)
        self.linearTrendLayout.setObjectName("linearTrendLayout")
        self.label_4 = QtWidgets.QLabel(self.pageLinearTrendPlot)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.linearTrendLayout.addWidget(self.label_4)
        self.linearTreandPlotLayout = QtWidgets.QVBoxLayout()
        self.linearTreandPlotLayout.setObjectName("linearTreandPlotLayout")
        self.linearTrendLayout.addLayout(self.linearTreandPlotLayout)
        self.verticalLayout_9.addLayout(self.linearTrendLayout)
        self.stackedWidgetPlots.addWidget(self.pageLinearTrendPlot)
        self.pageNoRegSnrPlot = QtWidgets.QWidget()
        self.pageNoRegSnrPlot.setObjectName("pageNoRegSnrPlot")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.pageNoRegSnrPlot)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.noRegSnrLayout = QtWidgets.QVBoxLayout()
        self.noRegSnrLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.noRegSnrLayout.setContentsMargins(0, -1, -1, -1)
        self.noRegSnrLayout.setObjectName("noRegSnrLayout")
        self.label_5 = QtWidgets.QLabel(self.pageNoRegSnrPlot)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.noRegSnrLayout.addWidget(self.label_5)
        self.noRegSnrPlotLayout = QtWidgets.QVBoxLayout()
        self.noRegSnrPlotLayout.setObjectName("noRegSnrPlotLayout")
        self.noRegSnrLayout.addLayout(self.noRegSnrPlotLayout)
        self.verticalLayout_26.addLayout(self.noRegSnrLayout)
        self.stackedWidgetPlots.addWidget(self.pageNoRegSnrPlot)
        self.pageDvarsPlot = QtWidgets.QWidget()
        self.pageDvarsPlot.setObjectName("pageDvarsPlot")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.pageDvarsPlot)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.dvarsLayout = QtWidgets.QVBoxLayout()
        self.dvarsLayout.setObjectName("dvarsLayout")
        self.label_6 = QtWidgets.QLabel(self.pageDvarsPlot)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.dvarsLayout.addWidget(self.label_6)
        self.dvarsPlotLayout = QtWidgets.QVBoxLayout()
        self.dvarsPlotLayout.setObjectName("dvarsPlotLayout")
        self.dvarsLayout.addLayout(self.dvarsPlotLayout)
        self.verticalLayout_24.addLayout(self.dvarsLayout)
        self.stackedWidgetPlots.addWidget(self.pageDvarsPlot)
        self.horizontalLayout_3.addWidget(self.stackedWidgetPlots)
        self.menuLayout = QtWidgets.QVBoxLayout()
        self.menuLayout.setContentsMargins(-1, -1, -1, 240)
        self.menuLayout.setObjectName("menuLayout")
        self.comboBox = QtWidgets.QComboBox(rtQA)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.menuLayout.addWidget(self.comboBox)
        self.stackedWidgetOptions = QtWidgets.QStackedWidget(rtQA)
        self.stackedWidgetOptions.setObjectName("stackedWidgetOptions")
        self.pageSnrOptions = QtWidgets.QWidget()
        self.pageSnrOptions.setObjectName("pageSnrOptions")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pageSnrOptions)
        self.verticalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tsCheckBox = QtWidgets.QCheckBox(self.pageSnrOptions)
        self.tsCheckBox.setChecked(True)
        self.tsCheckBox.setObjectName("tsCheckBox")
        self.verticalLayout_5.addWidget(self.tsCheckBox)
        self.volumeCheckBox = QtWidgets.QCheckBox(self.pageSnrOptions)
        self.volumeCheckBox.setObjectName("volumeCheckBox")
        self.verticalLayout_5.addWidget(self.volumeCheckBox)
        self.valuesLabel = QtWidgets.QLabel(self.pageSnrOptions)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.valuesLabel.setFont(font)
        self.valuesLabel.setText("")
        self.valuesLabel.setObjectName("valuesLabel")
        self.verticalLayout_5.addWidget(self.valuesLabel)
        spacerItem = QtWidgets.QSpacerItem(77, 424, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.stackedWidgetOptions.addWidget(self.pageSnrOptions)
        self.pageMcmdOptions = QtWidgets.QWidget()
        self.pageMcmdOptions.setObjectName("pageMcmdOptions")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.pageMcmdOptions)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.groupBox = QtWidgets.QGroupBox(self.pageMcmdOptions)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.fdRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.fdRadioButton.setChecked(True)
        self.fdRadioButton.setObjectName("fdRadioButton")
        self.verticalLayout_14.addWidget(self.fdRadioButton)
        self.mcrRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.mcrRadioButton.setObjectName("mcrRadioButton")
        self.verticalLayout_14.addWidget(self.mcrRadioButton)
        self.verticalLayout_15.addWidget(self.groupBox)
        self.mcmdValuesLabel = QtWidgets.QLabel(self.pageMcmdOptions)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mcmdValuesLabel.setFont(font)
        self.mcmdValuesLabel.setText("")
        self.mcmdValuesLabel.setObjectName("mcmdValuesLabel")
        self.verticalLayout_15.addWidget(self.mcmdValuesLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 329, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem1)
        self.stackedWidgetOptions.addWidget(self.pageMcmdOptions)
        self.pageCnrOptions = QtWidgets.QWidget()
        self.pageCnrOptions.setObjectName("pageCnrOptions")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.pageCnrOptions)
        self.verticalLayout_10.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem2 = QtWidgets.QSpacerItem(20, 407, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem2)
        self.stackedWidgetOptions.addWidget(self.pageCnrOptions)
        self.pageSpikes = QtWidgets.QWidget()
        self.pageSpikes.setObjectName("pageSpikes")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.pageSpikes)
        self.verticalLayout_20.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.spikesLabel = QtWidgets.QLabel(self.pageSpikes)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spikesLabel.setFont(font)
        self.spikesLabel.setText("")
        self.spikesLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spikesLabel.setObjectName("spikesLabel")
        self.verticalLayout_20.addWidget(self.spikesLabel)
        spacerItem3 = QtWidgets.QSpacerItem(20, 419, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem3)
        self.stackedWidgetOptions.addWidget(self.pageSpikes)
        self.pageMse = QtWidgets.QWidget()
        self.pageMse.setObjectName("pageMse")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.pageMse)
        self.verticalLayout_21.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.mseLabel = QtWidgets.QLabel(self.pageMse)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mseLabel.setFont(font)
        self.mseLabel.setText("")
        self.mseLabel.setObjectName("mseLabel")
        self.verticalLayout_21.addWidget(self.mseLabel)
        spacerItem4 = QtWidgets.QSpacerItem(20, 424, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem4)
        self.stackedWidgetOptions.addWidget(self.pageMse)
        self.pageTrend = QtWidgets.QWidget()
        self.pageTrend.setMaximumSize(QtCore.QSize(159, 497))
        self.pageTrend.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pageTrend.setObjectName("pageTrend")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.pageTrend)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.trendLabel = QtWidgets.QLabel(self.pageTrend)
        self.trendLabel.setMaximumSize(QtCore.QSize(141, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trendLabel.setFont(font)
        self.trendLabel.setText("")
        self.trendLabel.setObjectName("trendLabel")
        self.verticalLayout_22.addWidget(self.trendLabel)
        spacerItem5 = QtWidgets.QSpacerItem(20, 476, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_22.addItem(spacerItem5)
        self.stackedWidgetOptions.addWidget(self.pageTrend)
        self.pageNoRegSnr = QtWidgets.QWidget()
        self.pageNoRegSnr.setObjectName("pageNoRegSnr")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.pageNoRegSnr)
        self.verticalLayout_25.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.noRegSnrValueLabel = QtWidgets.QLabel(self.pageNoRegSnr)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.noRegSnrValueLabel.setFont(font)
        self.noRegSnrValueLabel.setText("")
        self.noRegSnrValueLabel.setObjectName("noRegSnrValueLabel")
        self.verticalLayout_25.addWidget(self.noRegSnrValueLabel)
        spacerItem6 = QtWidgets.QSpacerItem(20, 168, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem6)
        self.stackedWidgetOptions.addWidget(self.pageNoRegSnr)
        self.pageDvars = QtWidgets.QWidget()
        self.pageDvars.setObjectName("pageDvars")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.pageDvars)
        self.verticalLayout_27.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.dvarsLabel = QtWidgets.QLabel(self.pageDvars)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dvarsLabel.setFont(font)
        self.dvarsLabel.setText("")
        self.dvarsLabel.setObjectName("dvarsLabel")
        self.verticalLayout_27.addWidget(self.dvarsLabel)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_27.addItem(spacerItem7)
        self.stackedWidgetOptions.addWidget(self.pageDvars)
        self.menuLayout.addWidget(self.stackedWidgetOptions)
        self.roiGroupBox = QtWidgets.QGroupBox(rtQA)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.roiGroupBox.setFont(font)
        self.roiGroupBox.setObjectName("roiGroupBox")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.roiGroupBox)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.groupBoxLayout = QtWidgets.QVBoxLayout()
        self.groupBoxLayout.setObjectName("groupBoxLayout")
        self.verticalLayout_23.addLayout(self.groupBoxLayout)
        self.menuLayout.addWidget(self.roiGroupBox)
        self.horizontalLayout_3.addLayout(self.menuLayout)
        self.horizontalLayout_3.setStretch(0, 1)

        self.retranslateUi(rtQA)
        self.stackedWidgetPlots.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(0)
        self.stackedWidgetOptions.setCurrentIndex(0)
        self.comboBox.currentIndexChanged['int'].connect(self.stackedWidgetPlots.setCurrentIndex)
        self.comboBox.currentIndexChanged['int'].connect(self.stackedWidgetOptions.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(rtQA)

    def retranslateUi(self, rtQA):
        _translate = QtCore.QCoreApplication.translate
        rtQA.setWindowTitle(_translate("rtQA", "rtQA"))
        self.label.setText(_translate("rtQA", "Signal-to-Noise Ratio"))
        self.fdLabel.setText(_translate("rtQA", "fdLabel"))
        self.tdLabel.setText(_translate("rtQA", "tdLabel"))
        self.rdLabel.setText(_translate("rtQA", "rdLabel"))
        self.cnrLabel.setText(_translate("rtQA", "Contrast-to-Noise Ratio"))
        self.labelMean.setText(_translate("rtQA", "TextLabel"))
        self.labelVar.setText(_translate("rtQA", "TextLabel"))
        self.label_2.setText(_translate("rtQA", "Spikes"))
        self.label_3.setText(_translate("rtQA", "Mean squared error estimation of Kalman filter performance"))
        self.label_4.setText(_translate("rtQA", "Linear trend beta coefficients"))
        self.label_5.setText(_translate("rtQA", "No regulation Signal-to-Noise Ratio"))
        self.label_6.setText(_translate("rtQA", "DVARS"))
        self.comboBox.setItemText(0, _translate("rtQA", "SNR"))
        self.comboBox.setItemText(1, _translate("rtQA", "Motion correction"))
        self.comboBox.setItemText(2, _translate("rtQA", "CNR"))
        self.comboBox.setItemText(3, _translate("rtQA", "Spikes"))
        self.comboBox.setItemText(4, _translate("rtQA", "Kalman performance"))
        self.comboBox.setItemText(5, _translate("rtQA", "Linear trend"))
        self.comboBox.setItemText(6, _translate("rtQA", "no reg SNR"))
        self.comboBox.setItemText(7, _translate("rtQA", "DVARS"))
        self.tsCheckBox.setText(_translate("rtQA", "Time series"))
        self.volumeCheckBox.setText(_translate("rtQA", "Volume"))
        self.groupBox.setTitle(_translate("rtQA", "Submodes"))
        self.fdRadioButton.setText(_translate("rtQA", "Framewise displacement"))
        self.mcrRadioButton.setText(_translate("rtQA", "Micro displacement"))
        self.roiGroupBox.setTitle(_translate("rtQA", "Displayed ROI(s)"))

